ALTER TABLE "Reminders" ALTER COLUMN "repeat" TYPE VARCHAR(32);
ALTER TABLE "Reminders" ADD COLUMN IF NOT EXISTS "recurrence" JSONB;
ALTER TABLE "Reminders" ADD COLUMN IF NOT EXISTS "occurrences_fired" INTEGER NOT NULL DEFAULT 0;
